### ISSUE TITLE
warn user if/when text is truncated

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#107] opened 2017-06-15 19:49 UTC
The new truncation features look to be working very well, but there's one edge case.

When I create a new entry, I am able to cut and paste text repeatedly past the 128 character limit. The website accepts the input and then cuts it down later.

Now, if I try to go over the limit again, it doesn't let me.

It looks like we can fix things one of two ways:

* don't allow the user to go over 128 characters the first time they input anything. (My preferred choice. It's simpler, and the user will get the point)
* if their entry is more than 128 characters (or 64 for the pseudonym) then print a warning if text has been cut down (ideally, we'd say X fields had been cut down)

Text to cut/paste below to make it quicker
abcdefghijklmnop qrstuvwxyz 12345 67890

**Comment by jmacdotorg** [comment] 2017-08-08 15:02
I'm not able to reproduce this in either Chrome or Safari (the title field shows a hard input limit on the first screen), so I am closing this. Lemme know if I missed something.

**Closed by jmacdotorg** 2017-08-08 15:02 UTC
