### ISSUE TITLE
Update interpreters

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#124] opened 2017-08-02 03:53 UTC
- [x] Basic stylehint support
  - [ ] Finalise stylehint protocol
- [x] Garglk text formatting support
- [ ] Update ZVM to use the new functions
- [x] Update Quixe to use the new functions?
- [x] Update html generation
- [ ] Transcript recording

**Comment by jmacdotorg** [comment] 2017-08-02 19:47
> Or if you just want to get the files from the repository, the master branch is stable.

That's good enough for me! Thanks.

**Comment by VictorGijsbers** [comment] 2018-08-21 08:35
According to Dannii in this topic: https://www.intfiction.org/forum/viewtopic.php?f=7&t=26498 , the IFComp website's use of an old version of Parchment is the cause for an unwanted final message appearing in my upcoming IFComp 2018 entry. If this could be fixed before the comp, that would obviously be great!

**Comment by jmacdotorg** [comment] 2018-08-22 02:13
Thank you for the nudge! I'll get on this presently.

**Comment by VictorGijsbers** [comment] 2018-08-22 13:29
Thanks!

**Comment by jmacdotorg** [comment] 2018-08-29 17:06
@curiousdannii - With the latest Parchment branch, I'm seeing issues regarding the display of Basic Help Menu. For a minimal example, see: http://jmac.org/misc/parchment_test/

Type HELP and then try moving the selection cursor up and down.

I'm hesitant to merge this behavior into IFComp production, naturally, so ideas or solutions would be quite welcome.

**Comment by curiousdannii** [comment] 2018-08-30 01:06
I'll try to get this fixed ASAP.

An alternative would be to directly use ZVM with GlkOte (from Quixe) but then it wouldn't have any colour support.

**Comment by jmacdotorg** [comment] 2019-02-16 17:21
![](https://github.trello.services/images/mini-trello-icon.png) [Update Parchment](https://trello.com/c/KSR9okh1/27-update-parchment)

**Comment by curiousdannii** [comment] 2019-08-28 02:17
So I've added basic stylehint support to GlkOte. Garglk text formatting stuff still to come.

I found the https://github.com/iftechfoundation/ifcomp/tree/master/IFComp/root/static/interpreter folder. With both ZVM and Quixe sharing GlkOte, it would make sense to rearrange how the folders are organised. I can update files there as I go. How would you feel about giving me commit access? :)

Where is the html of the play pages generated?

**Comment by curiousdannii** [comment] 2019-08-28 02:18
- [x] Basic stylehint support
  - [ ] Finalise stylehint protocol
- [ ] Garglk text formatting support
- [ ] Update ZVM to use the new functions
- [ ] Update Quixe to use the new functions?
- [ ] Update html generation
- [ ] Add a dark mode?
- [ ] Add Hugo?

**Comment by jmacdotorg** [comment] 2019-09-04 11:42
@curiousdannii,

For now, I would encourage you to fork the project, work on your own copy, and then submit pull requests with proposed changes!

The library that does the most work for generating play pages is [IFComp::Schema::Result::Entry](https://github.com/iftechfoundation/ifcomp/blob/master/IFComp/lib/IFComp/Schema/Result/Entry.pm), the object class for IFComp Entries. See especially the method definitions that start around line 1090, with the `_create_parchment_page` sub.

I honestly haven't been sweating much about supporting any browser that doesn't itself support modern web standards.

**Comment by jmacdotorg** [comment] 2019-09-30 18:56
Closed, with #174.

**Comment by jmacdotorg** [comment] 2019-10-01 00:43
Oops, closed this prematurely. The glulx interpreters have indeed been updated, but the z-code ones still need updating. Re-opening.

**Comment by jmacdotorg** [comment] 2020-04-01 23:16
Changing this from "enhancement" to "bug" after last year. Whatever's currently running on ifcomp.org has some serious issues on modern browsers, most especially with the graphical effect of the insertion point overlapping the `>` prompt character on a fresh input line.

**Closed** 2020-08-17 15:00 UTC
Labels: blocked
