### ISSUE TITLE
Our 500 error page should be more informative

### ISSUE THREAD

**Issue by mjmusante** [iftechfoundation/ifcomp#326] opened 2021-07-02 00:16 UTC
We currently have the default multilingual "please come back later" for 500 errors. It should provide information about how to contact the comp cheez and a link to file issues on github

**Comment by mjmusante** [comment] 2021-07-02 00:17
Adam pointed me at this doc https://metacpan.org/pod/Plack::Middleware::ErrorDocument

**Comment by curiousdannii** [comment] 2021-07-02 02:22
Duplicate of #167

**Closed by curiousdannii** 2021-07-02 02:22 UTC
